/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedResponderRouteImport } from './routes/_authenticated/responder'
import { Route as AuthenticatedTouristRouteImport } from './routes/_authenticated/tourist'
import { Route as PublicResourcesRouteImport } from './routes/public/resources'
import { Route as PublicSafetyRouteImport } from './routes/public/safety'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAlertsRouteImport } from './routes/_authenticated/admin/alerts'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminMapRouteImport } from './routes/_authenticated/admin/map'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as AuthenticatedAdminSafetyRouteImport } from './routes/_authenticated/admin/safety'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedResponderIndexRouteImport } from './routes/_authenticated/responder/index'
import { Route as AuthenticatedResponderAssignedRouteImport } from './routes/_authenticated/responder/assigned'
import { Route as AuthenticatedResponderHistoryRouteImport } from './routes/_authenticated/responder/history'
import { Route as AuthenticatedResponderMapRouteImport } from './routes/_authenticated/responder/map'
import { Route as AuthenticatedResponderNotificationsRouteImport } from './routes/_authenticated/responder/notifications'
import { Route as AuthenticatedResponderProfileRouteImport } from './routes/_authenticated/responder/profile'
import { Route as AuthenticatedTouristIndexRouteImport } from './routes/_authenticated/tourist/index'
import { Route as AuthenticatedTouristAlertsRouteImport } from './routes/_authenticated/tourist/alerts'
import { Route as AuthenticatedTouristAssistRouteImport } from './routes/_authenticated/tourist/assist'
import { Route as AuthenticatedTouristContactsRouteImport } from './routes/_authenticated/tourist/contacts'
import { Route as AuthenticatedTouristEmergencyRouteImport } from './routes/_authenticated/tourist/emergency'
import { Route as AuthenticatedTouristMapRouteImport } from './routes/_authenticated/tourist/map'
import { Route as AuthenticatedTouristNotificationsRouteImport } from './routes/_authenticated/tourist/notifications'
import { Route as AuthenticatedTouristProfileRouteImport } from './routes/_authenticated/tourist/profile'
import { Route as AuthenticatedTouristReportRouteImport } from './routes/_authenticated/tourist/report'
import { Route as AuthenticatedTouristResourcesRouteImport } from './routes/_authenticated/tourist/resources'
import { Route as AuthenticatedTouristSafetyRouteImport } from './routes/_authenticated/tourist/safety'
import { Route as AuthenticatedTouristSosRouteImport } from './routes/_authenticated/tourist/sos'
import { Route as AuthenticatedAdminIncidentsIndexRouteImport } from './routes/_authenticated/admin/incidents/index'
import { Route as AuthenticatedAdminIncidentsIncidentIdRouteImport } from './routes/_authenticated/admin/incidents/$incidentId'
import { Route as AuthenticatedResponderIncidentsIndexRouteImport } from './routes/_authenticated/responder/incidents/index'
import { Route as AuthenticatedResponderIncidentsIncidentIdRouteImport } from './routes/_authenticated/responder/incidents/$incidentId'
import { Route as AuthenticatedTouristIncidentsIndexRouteImport } from './routes/_authenticated/tourist/incidents/index'
import { Route as AuthenticatedTouristIncidentsIncidentIdRouteImport } from './routes/_authenticated/tourist/incidents/$incidentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponderRoute = AuthenticatedResponderRouteImport.update({
  id: '/responder',
  path: '/responder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTouristRoute = AuthenticatedTouristRouteImport.update({
  id: '/tourist',
  path: '/tourist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/public/resources',
  path: '/public/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSafetyRoute = PublicSafetyRouteImport.update({
  id: '/public/safety',
  path: '/public/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAlertsRoute =
  AuthenticatedAdminAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMapRoute = AuthenticatedAdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSafetyRoute =
  AuthenticatedAdminSafetyRouteImport.update({
    id: '/safety',
    path: '/safety',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedResponderIndexRoute =
  AuthenticatedResponderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedResponderAssignedRoute =
  AuthenticatedResponderAssignedRouteImport.update({
    id: '/assigned',
    path: '/assigned',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedResponderHistoryRoute =
  AuthenticatedResponderHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedResponderMapRoute =
  AuthenticatedResponderMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedResponderNotificationsRoute =
  AuthenticatedResponderNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedResponderProfileRoute =
  AuthenticatedResponderProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedTouristIndexRoute =
  AuthenticatedTouristIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristAlertsRoute =
  AuthenticatedTouristAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristAssistRoute =
  AuthenticatedTouristAssistRouteImport.update({
    id: '/assist',
    path: '/assist',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristContactsRoute =
  AuthenticatedTouristContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristEmergencyRoute =
  AuthenticatedTouristEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristMapRoute = AuthenticatedTouristMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedTouristRoute,
} as any)
const AuthenticatedTouristNotificationsRoute =
  AuthenticatedTouristNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristProfileRoute =
  AuthenticatedTouristProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristReportRoute =
  AuthenticatedTouristReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristResourcesRoute =
  AuthenticatedTouristResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristSafetyRoute =
  AuthenticatedTouristSafetyRouteImport.update({
    id: '/safety',
    path: '/safety',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristSosRoute = AuthenticatedTouristSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedTouristRoute,
} as any)
const AuthenticatedAdminIncidentsIndexRoute =
  AuthenticatedAdminIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIncidentsIncidentIdRoute =
  AuthenticatedAdminIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedResponderIncidentsIndexRoute =
  AuthenticatedResponderIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedResponderIncidentsIncidentIdRoute =
  AuthenticatedResponderIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthenticatedResponderRoute,
  } as any)
const AuthenticatedTouristIncidentsIndexRoute =
  AuthenticatedTouristIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)
const AuthenticatedTouristIncidentsIncidentIdRoute =
  AuthenticatedTouristIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthenticatedTouristRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/responder': typeof AuthenticatedResponderRouteWithChildren
  '/tourist': typeof AuthenticatedTouristRouteWithChildren
  '/public/resources': typeof PublicResourcesRoute
  '/public/safety': typeof PublicSafetyRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/map': typeof AuthenticatedAdminMapRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/responder/assigned': typeof AuthenticatedResponderAssignedRoute
  '/responder/history': typeof AuthenticatedResponderHistoryRoute
  '/responder/map': typeof AuthenticatedResponderMapRoute
  '/responder/notifications': typeof AuthenticatedResponderNotificationsRoute
  '/responder/profile': typeof AuthenticatedResponderProfileRoute
  '/tourist/alerts': typeof AuthenticatedTouristAlertsRoute
  '/tourist/assist': typeof AuthenticatedTouristAssistRoute
  '/tourist/contacts': typeof AuthenticatedTouristContactsRoute
  '/tourist/emergency': typeof AuthenticatedTouristEmergencyRoute
  '/tourist/map': typeof AuthenticatedTouristMapRoute
  '/tourist/notifications': typeof AuthenticatedTouristNotificationsRoute
  '/tourist/profile': typeof AuthenticatedTouristProfileRoute
  '/tourist/report': typeof AuthenticatedTouristReportRoute
  '/tourist/resources': typeof AuthenticatedTouristResourcesRoute
  '/tourist/safety': typeof AuthenticatedTouristSafetyRoute
  '/tourist/sos': typeof AuthenticatedTouristSosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/responder/': typeof AuthenticatedResponderIndexRoute
  '/tourist/': typeof AuthenticatedTouristIndexRoute
  '/admin/incidents/$incidentId': typeof AuthenticatedAdminIncidentsIncidentIdRoute
  '/responder/incidents/$incidentId': typeof AuthenticatedResponderIncidentsIncidentIdRoute
  '/tourist/incidents/$incidentId': typeof AuthenticatedTouristIncidentsIncidentIdRoute
  '/admin/incidents/': typeof AuthenticatedAdminIncidentsIndexRoute
  '/responder/incidents/': typeof AuthenticatedResponderIncidentsIndexRoute
  '/tourist/incidents/': typeof AuthenticatedTouristIncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/public/resources': typeof PublicResourcesRoute
  '/public/safety': typeof PublicSafetyRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/map': typeof AuthenticatedAdminMapRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/responder/assigned': typeof AuthenticatedResponderAssignedRoute
  '/responder/history': typeof AuthenticatedResponderHistoryRoute
  '/responder/map': typeof AuthenticatedResponderMapRoute
  '/responder/notifications': typeof AuthenticatedResponderNotificationsRoute
  '/responder/profile': typeof AuthenticatedResponderProfileRoute
  '/tourist/alerts': typeof AuthenticatedTouristAlertsRoute
  '/tourist/assist': typeof AuthenticatedTouristAssistRoute
  '/tourist/contacts': typeof AuthenticatedTouristContactsRoute
  '/tourist/emergency': typeof AuthenticatedTouristEmergencyRoute
  '/tourist/map': typeof AuthenticatedTouristMapRoute
  '/tourist/notifications': typeof AuthenticatedTouristNotificationsRoute
  '/tourist/profile': typeof AuthenticatedTouristProfileRoute
  '/tourist/report': typeof AuthenticatedTouristReportRoute
  '/tourist/resources': typeof AuthenticatedTouristResourcesRoute
  '/tourist/safety': typeof AuthenticatedTouristSafetyRoute
  '/tourist/sos': typeof AuthenticatedTouristSosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/responder': typeof AuthenticatedResponderIndexRoute
  '/tourist': typeof AuthenticatedTouristIndexRoute
  '/admin/incidents/$incidentId': typeof AuthenticatedAdminIncidentsIncidentIdRoute
  '/responder/incidents/$incidentId': typeof AuthenticatedResponderIncidentsIncidentIdRoute
  '/tourist/incidents/$incidentId': typeof AuthenticatedTouristIncidentsIncidentIdRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsIndexRoute
  '/responder/incidents': typeof AuthenticatedResponderIncidentsIndexRoute
  '/tourist/incidents': typeof AuthenticatedTouristIncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/responder': typeof AuthenticatedResponderRouteWithChildren
  '/_authenticated/tourist': typeof AuthenticatedTouristRouteWithChildren
  '/public/resources': typeof PublicResourcesRoute
  '/public/safety': typeof PublicSafetyRoute
  '/_authenticated/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/map': typeof AuthenticatedAdminMapRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/responder/assigned': typeof AuthenticatedResponderAssignedRoute
  '/_authenticated/responder/history': typeof AuthenticatedResponderHistoryRoute
  '/_authenticated/responder/map': typeof AuthenticatedResponderMapRoute
  '/_authenticated/responder/notifications': typeof AuthenticatedResponderNotificationsRoute
  '/_authenticated/responder/profile': typeof AuthenticatedResponderProfileRoute
  '/_authenticated/tourist/alerts': typeof AuthenticatedTouristAlertsRoute
  '/_authenticated/tourist/assist': typeof AuthenticatedTouristAssistRoute
  '/_authenticated/tourist/contacts': typeof AuthenticatedTouristContactsRoute
  '/_authenticated/tourist/emergency': typeof AuthenticatedTouristEmergencyRoute
  '/_authenticated/tourist/map': typeof AuthenticatedTouristMapRoute
  '/_authenticated/tourist/notifications': typeof AuthenticatedTouristNotificationsRoute
  '/_authenticated/tourist/profile': typeof AuthenticatedTouristProfileRoute
  '/_authenticated/tourist/report': typeof AuthenticatedTouristReportRoute
  '/_authenticated/tourist/resources': typeof AuthenticatedTouristResourcesRoute
  '/_authenticated/tourist/safety': typeof AuthenticatedTouristSafetyRoute
  '/_authenticated/tourist/sos': typeof AuthenticatedTouristSosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/responder/': typeof AuthenticatedResponderIndexRoute
  '/_authenticated/tourist/': typeof AuthenticatedTouristIndexRoute
  '/_authenticated/admin/incidents/$incidentId': typeof AuthenticatedAdminIncidentsIncidentIdRoute
  '/_authenticated/responder/incidents/$incidentId': typeof AuthenticatedResponderIncidentsIncidentIdRoute
  '/_authenticated/tourist/incidents/$incidentId': typeof AuthenticatedTouristIncidentsIncidentIdRoute
  '/_authenticated/admin/incidents/': typeof AuthenticatedAdminIncidentsIndexRoute
  '/_authenticated/responder/incidents/': typeof AuthenticatedResponderIncidentsIndexRoute
  '/_authenticated/tourist/incidents/': typeof AuthenticatedTouristIncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/home'
    | '/responder'
    | '/tourist'
    | '/public/resources'
    | '/public/safety'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/map'
    | '/admin/notifications'
    | '/admin/resources'
    | '/admin/safety'
    | '/admin/users'
    | '/responder/assigned'
    | '/responder/history'
    | '/responder/map'
    | '/responder/notifications'
    | '/responder/profile'
    | '/tourist/alerts'
    | '/tourist/assist'
    | '/tourist/contacts'
    | '/tourist/emergency'
    | '/tourist/map'
    | '/tourist/notifications'
    | '/tourist/profile'
    | '/tourist/report'
    | '/tourist/resources'
    | '/tourist/safety'
    | '/tourist/sos'
    | '/admin/'
    | '/responder/'
    | '/tourist/'
    | '/admin/incidents/$incidentId'
    | '/responder/incidents/$incidentId'
    | '/tourist/incidents/$incidentId'
    | '/admin/incidents/'
    | '/responder/incidents/'
    | '/tourist/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/home'
    | '/public/resources'
    | '/public/safety'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/map'
    | '/admin/notifications'
    | '/admin/resources'
    | '/admin/safety'
    | '/admin/users'
    | '/responder/assigned'
    | '/responder/history'
    | '/responder/map'
    | '/responder/notifications'
    | '/responder/profile'
    | '/tourist/alerts'
    | '/tourist/assist'
    | '/tourist/contacts'
    | '/tourist/emergency'
    | '/tourist/map'
    | '/tourist/notifications'
    | '/tourist/profile'
    | '/tourist/report'
    | '/tourist/resources'
    | '/tourist/safety'
    | '/tourist/sos'
    | '/admin'
    | '/responder'
    | '/tourist'
    | '/admin/incidents/$incidentId'
    | '/responder/incidents/$incidentId'
    | '/tourist/incidents/$incidentId'
    | '/admin/incidents'
    | '/responder/incidents'
    | '/tourist/incidents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/home'
    | '/_authenticated/responder'
    | '/_authenticated/tourist'
    | '/public/resources'
    | '/public/safety'
    | '/_authenticated/admin/alerts'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/map'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/safety'
    | '/_authenticated/admin/users'
    | '/_authenticated/responder/assigned'
    | '/_authenticated/responder/history'
    | '/_authenticated/responder/map'
    | '/_authenticated/responder/notifications'
    | '/_authenticated/responder/profile'
    | '/_authenticated/tourist/alerts'
    | '/_authenticated/tourist/assist'
    | '/_authenticated/tourist/contacts'
    | '/_authenticated/tourist/emergency'
    | '/_authenticated/tourist/map'
    | '/_authenticated/tourist/notifications'
    | '/_authenticated/tourist/profile'
    | '/_authenticated/tourist/report'
    | '/_authenticated/tourist/resources'
    | '/_authenticated/tourist/safety'
    | '/_authenticated/tourist/sos'
    | '/_authenticated/admin/'
    | '/_authenticated/responder/'
    | '/_authenticated/tourist/'
    | '/_authenticated/admin/incidents/$incidentId'
    | '/_authenticated/responder/incidents/$incidentId'
    | '/_authenticated/tourist/incidents/$incidentId'
    | '/_authenticated/admin/incidents/'
    | '/_authenticated/responder/incidents/'
    | '/_authenticated/tourist/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  PublicResourcesRoute: typeof PublicResourcesRoute
  PublicSafetyRoute: typeof PublicSafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responder': {
      id: '/_authenticated/responder'
      path: '/responder'
      fullPath: '/responder'
      preLoaderRoute: typeof AuthenticatedResponderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tourist': {
      id: '/_authenticated/tourist'
      path: '/tourist'
      fullPath: '/tourist'
      preLoaderRoute: typeof AuthenticatedTouristRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/public/resources': {
      id: '/public/resources'
      path: '/public/resources'
      fullPath: '/public/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/safety': {
      id: '/public/safety'
      path: '/public/safety'
      fullPath: '/public/safety'
      preLoaderRoute: typeof PublicSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alerts': {
      id: '/_authenticated/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AuthenticatedAdminAlertsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/map': {
      id: '/_authenticated/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AuthenticatedAdminMapRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/safety': {
      id: '/_authenticated/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AuthenticatedAdminSafetyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/responder/': {
      id: '/_authenticated/responder/'
      path: '/'
      fullPath: '/responder/'
      preLoaderRoute: typeof AuthenticatedResponderIndexRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/responder/assigned': {
      id: '/_authenticated/responder/assigned'
      path: '/assigned'
      fullPath: '/responder/assigned'
      preLoaderRoute: typeof AuthenticatedResponderAssignedRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/responder/history': {
      id: '/_authenticated/responder/history'
      path: '/history'
      fullPath: '/responder/history'
      preLoaderRoute: typeof AuthenticatedResponderHistoryRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/responder/map': {
      id: '/_authenticated/responder/map'
      path: '/map'
      fullPath: '/responder/map'
      preLoaderRoute: typeof AuthenticatedResponderMapRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/responder/notifications': {
      id: '/_authenticated/responder/notifications'
      path: '/notifications'
      fullPath: '/responder/notifications'
      preLoaderRoute: typeof AuthenticatedResponderNotificationsRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/responder/profile': {
      id: '/_authenticated/responder/profile'
      path: '/profile'
      fullPath: '/responder/profile'
      preLoaderRoute: typeof AuthenticatedResponderProfileRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/tourist/': {
      id: '/_authenticated/tourist/'
      path: '/'
      fullPath: '/tourist/'
      preLoaderRoute: typeof AuthenticatedTouristIndexRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/alerts': {
      id: '/_authenticated/tourist/alerts'
      path: '/alerts'
      fullPath: '/tourist/alerts'
      preLoaderRoute: typeof AuthenticatedTouristAlertsRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/assist': {
      id: '/_authenticated/tourist/assist'
      path: '/assist'
      fullPath: '/tourist/assist'
      preLoaderRoute: typeof AuthenticatedTouristAssistRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/contacts': {
      id: '/_authenticated/tourist/contacts'
      path: '/contacts'
      fullPath: '/tourist/contacts'
      preLoaderRoute: typeof AuthenticatedTouristContactsRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/emergency': {
      id: '/_authenticated/tourist/emergency'
      path: '/emergency'
      fullPath: '/tourist/emergency'
      preLoaderRoute: typeof AuthenticatedTouristEmergencyRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/map': {
      id: '/_authenticated/tourist/map'
      path: '/map'
      fullPath: '/tourist/map'
      preLoaderRoute: typeof AuthenticatedTouristMapRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/notifications': {
      id: '/_authenticated/tourist/notifications'
      path: '/notifications'
      fullPath: '/tourist/notifications'
      preLoaderRoute: typeof AuthenticatedTouristNotificationsRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/profile': {
      id: '/_authenticated/tourist/profile'
      path: '/profile'
      fullPath: '/tourist/profile'
      preLoaderRoute: typeof AuthenticatedTouristProfileRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/report': {
      id: '/_authenticated/tourist/report'
      path: '/report'
      fullPath: '/tourist/report'
      preLoaderRoute: typeof AuthenticatedTouristReportRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/resources': {
      id: '/_authenticated/tourist/resources'
      path: '/resources'
      fullPath: '/tourist/resources'
      preLoaderRoute: typeof AuthenticatedTouristResourcesRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/safety': {
      id: '/_authenticated/tourist/safety'
      path: '/safety'
      fullPath: '/tourist/safety'
      preLoaderRoute: typeof AuthenticatedTouristSafetyRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/sos': {
      id: '/_authenticated/tourist/sos'
      path: '/sos'
      fullPath: '/tourist/sos'
      preLoaderRoute: typeof AuthenticatedTouristSosRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/admin/incidents/': {
      id: '/_authenticated/admin/incidents/'
      path: '/incidents'
      fullPath: '/admin/incidents/'
      preLoaderRoute: typeof AuthenticatedAdminIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/incidents/$incidentId': {
      id: '/_authenticated/admin/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/admin/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedAdminIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/responder/incidents/': {
      id: '/_authenticated/responder/incidents/'
      path: '/incidents'
      fullPath: '/responder/incidents/'
      preLoaderRoute: typeof AuthenticatedResponderIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/responder/incidents/$incidentId': {
      id: '/_authenticated/responder/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/responder/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedResponderIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedResponderRoute
    }
    '/_authenticated/tourist/incidents/': {
      id: '/_authenticated/tourist/incidents/'
      path: '/incidents'
      fullPath: '/tourist/incidents/'
      preLoaderRoute: typeof AuthenticatedTouristIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
    '/_authenticated/tourist/incidents/$incidentId': {
      id: '/_authenticated/tourist/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/tourist/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedTouristIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedTouristRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlertsRoute: typeof AuthenticatedAdminAlertsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminMapRoute: typeof AuthenticatedAdminMapRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSafetyRoute: typeof AuthenticatedAdminSafetyRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminIncidentsIncidentIdRoute: typeof AuthenticatedAdminIncidentsIncidentIdRoute
  AuthenticatedAdminIncidentsIndexRoute: typeof AuthenticatedAdminIncidentsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlertsRoute: AuthenticatedAdminAlertsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminMapRoute: AuthenticatedAdminMapRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminSafetyRoute: AuthenticatedAdminSafetyRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminIncidentsIncidentIdRoute:
    AuthenticatedAdminIncidentsIncidentIdRoute,
  AuthenticatedAdminIncidentsIndexRoute: AuthenticatedAdminIncidentsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedResponderRouteChildren {
  AuthenticatedResponderAssignedRoute: typeof AuthenticatedResponderAssignedRoute
  AuthenticatedResponderHistoryRoute: typeof AuthenticatedResponderHistoryRoute
  AuthenticatedResponderMapRoute: typeof AuthenticatedResponderMapRoute
  AuthenticatedResponderNotificationsRoute: typeof AuthenticatedResponderNotificationsRoute
  AuthenticatedResponderProfileRoute: typeof AuthenticatedResponderProfileRoute
  AuthenticatedResponderIndexRoute: typeof AuthenticatedResponderIndexRoute
  AuthenticatedResponderIncidentsIncidentIdRoute: typeof AuthenticatedResponderIncidentsIncidentIdRoute
  AuthenticatedResponderIncidentsIndexRoute: typeof AuthenticatedResponderIncidentsIndexRoute
}

const AuthenticatedResponderRouteChildren: AuthenticatedResponderRouteChildren =
  {
    AuthenticatedResponderAssignedRoute: AuthenticatedResponderAssignedRoute,
    AuthenticatedResponderHistoryRoute: AuthenticatedResponderHistoryRoute,
    AuthenticatedResponderMapRoute: AuthenticatedResponderMapRoute,
    AuthenticatedResponderNotificationsRoute:
      AuthenticatedResponderNotificationsRoute,
    AuthenticatedResponderProfileRoute: AuthenticatedResponderProfileRoute,
    AuthenticatedResponderIndexRoute: AuthenticatedResponderIndexRoute,
    AuthenticatedResponderIncidentsIncidentIdRoute:
      AuthenticatedResponderIncidentsIncidentIdRoute,
    AuthenticatedResponderIncidentsIndexRoute:
      AuthenticatedResponderIncidentsIndexRoute,
  }

const AuthenticatedResponderRouteWithChildren =
  AuthenticatedResponderRoute._addFileChildren(
    AuthenticatedResponderRouteChildren,
  )

interface AuthenticatedTouristRouteChildren {
  AuthenticatedTouristAlertsRoute: typeof AuthenticatedTouristAlertsRoute
  AuthenticatedTouristAssistRoute: typeof AuthenticatedTouristAssistRoute
  AuthenticatedTouristContactsRoute: typeof AuthenticatedTouristContactsRoute
  AuthenticatedTouristEmergencyRoute: typeof AuthenticatedTouristEmergencyRoute
  AuthenticatedTouristMapRoute: typeof AuthenticatedTouristMapRoute
  AuthenticatedTouristNotificationsRoute: typeof AuthenticatedTouristNotificationsRoute
  AuthenticatedTouristProfileRoute: typeof AuthenticatedTouristProfileRoute
  AuthenticatedTouristReportRoute: typeof AuthenticatedTouristReportRoute
  AuthenticatedTouristResourcesRoute: typeof AuthenticatedTouristResourcesRoute
  AuthenticatedTouristSafetyRoute: typeof AuthenticatedTouristSafetyRoute
  AuthenticatedTouristSosRoute: typeof AuthenticatedTouristSosRoute
  AuthenticatedTouristIndexRoute: typeof AuthenticatedTouristIndexRoute
  AuthenticatedTouristIncidentsIncidentIdRoute: typeof AuthenticatedTouristIncidentsIncidentIdRoute
  AuthenticatedTouristIncidentsIndexRoute: typeof AuthenticatedTouristIncidentsIndexRoute
}

const AuthenticatedTouristRouteChildren: AuthenticatedTouristRouteChildren = {
  AuthenticatedTouristAlertsRoute: AuthenticatedTouristAlertsRoute,
  AuthenticatedTouristAssistRoute: AuthenticatedTouristAssistRoute,
  AuthenticatedTouristContactsRoute: AuthenticatedTouristContactsRoute,
  AuthenticatedTouristEmergencyRoute: AuthenticatedTouristEmergencyRoute,
  AuthenticatedTouristMapRoute: AuthenticatedTouristMapRoute,
  AuthenticatedTouristNotificationsRoute:
    AuthenticatedTouristNotificationsRoute,
  AuthenticatedTouristProfileRoute: AuthenticatedTouristProfileRoute,
  AuthenticatedTouristReportRoute: AuthenticatedTouristReportRoute,
  AuthenticatedTouristResourcesRoute: AuthenticatedTouristResourcesRoute,
  AuthenticatedTouristSafetyRoute: AuthenticatedTouristSafetyRoute,
  AuthenticatedTouristSosRoute: AuthenticatedTouristSosRoute,
  AuthenticatedTouristIndexRoute: AuthenticatedTouristIndexRoute,
  AuthenticatedTouristIncidentsIncidentIdRoute:
    AuthenticatedTouristIncidentsIncidentIdRoute,
  AuthenticatedTouristIncidentsIndexRoute:
    AuthenticatedTouristIncidentsIndexRoute,
}

const AuthenticatedTouristRouteWithChildren =
  AuthenticatedTouristRoute._addFileChildren(AuthenticatedTouristRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedResponderRoute: typeof AuthenticatedResponderRouteWithChildren
  AuthenticatedTouristRoute: typeof AuthenticatedTouristRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedResponderRoute: AuthenticatedResponderRouteWithChildren,
  AuthenticatedTouristRoute: AuthenticatedTouristRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  PublicResourcesRoute: PublicResourcesRoute,
  PublicSafetyRoute: PublicSafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
